### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by mayuki** [mayuki/Rin#1]
- Client
    - [x] View: Timestamp
    - [x] Timeline: Trace integration
    - [ ] Error/Exception handling
    - [x] View: styling
    - [x] Reload when server-side upgraded
    - [x] View: grid splitter (WIP)
    - [x] Copy: LINQPad (using)
    - [x] View: make trace view scrollable
- Server
    - [ ] Access Control
    - [x] Error running on production environment
    - [ ] Persist records/PubSub
    - [ ] Trace level
    - Trace Collector
        - [x] log4net
        - [ ] NLog
        - [ ] EventSource
        - [ ] DiagnosticSource
- [ ] API Refactoring
